import React, { createContext, useContext, useEffect, useMemo, useState } from "react";

export type Lang = "en" | "de";

type I18nDict = Record<string, string>;

type DictMap = Record<Lang, I18nDict>;

type LanguageContextState = {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
};

const defaultLang: Lang = "en";
const storageKey = "site-lang";

const dictionaries: DictMap = {
  en: {
    "brand.name": "UGC Studio",
    "nav.services": "Services",
    "nav.howItWorks": "How It Works",
    "nav.pricing": "Pricing",
    "nav.testimonials": "Testimonials",
    "nav.faq": "FAQ",
    "nav.contact": "Contact",
    "cta.getQuote": "Get a UGC Quote",

    "hero.badge": "High-Impact UGC for Brands",
    "hero.title": "UGC that Converts",
    "hero.subtitle": "We script, cast, shoot, and edit user‑generated content that makes your product the star—optimized for TikTok, Reels, and Shorts. Fast turnaround, data‑driven hooks, usage rights included.",
    "hero.cta.aria": "Get a free UGC strategy call",
    "hero.cta.full": "Get a UGC Quote",
    "hero.cta.short": "Get Quote",
    "hero.note": "Free content strategy call + hook ideas included",
    "hero.stat.brands": "Brands Served",
    "hero.stat.videos": "Videos Delivered",
    "hero.stat.ctr": "Avg CTR Uplift",

    "services.badge": "UGC Services",
    "services.title.before": "End‑to‑End",
    "services.title.highlight": "UGC Production",
    "services.subtitle": "Script → cast → shoot → edit → deliver. Short‑form videos that feel native, sell benefits, and drive conversions across TikTok, Reels, and Shorts.",
    "services.items.0.title": "UGC Scripting & Hooks",
    "services.items.0.description": "High-converting scripts with proven hooks and CTAs tailored to your product and audience.",
    "services.items.0.benefit": "Scroll‑stopping openers",
    "services.items.1.title": "Creator Casting",
    "services.items.1.description": "We source on-brand creators across niches, demographics, and speaking styles that fit your brief.",
    "services.items.1.benefit": "On-brand faces",
    "services.items.2.title": "Shoot & Edit",
    "services.items.2.description": "End-to-end production: direction, lighting, audio, A‑roll/B‑roll capture, captions, and platform cuts.",
    "services.items.2.benefit": "Ready-to-post",
    "services.items.3.title": "Variations & Testing",
    "services.items.3.description": "Multiple hooks, angles, and lengths per concept so you can test and scale what performs.",
    "services.items.3.benefit": "Faster learnings",
    "services.items.4.title": "Performance Optimization",
    "services.items.4.description": "Creative analysis and iteration for higher CTR, watch time, and conversion across TikTok, Reels, Shorts.",
    "services.items.4.benefit": "Data‑driven wins",
    "services.items.5.title": "Usage Rights & Delivery",
    "services.items.5.description": "Clear usage rights, source files on request, and clean handoff in your preferred workspace.",
    "services.items.5.benefit": "No friction",

    "how.badge": "Our UGC Process",
    "how.title.pre": "How We",
    "how.title.highlight": "Create UGC",
    "how.subtitle": "From brief to final video in 5–7 days. Data-driven hooks, authentic creators, and platform-optimized editing.",
    "how.steps.0.step": "Step 1",
    "how.steps.0.title": "Brief & Strategy",
    "how.steps.0.desc": "Share your product, target audience, and campaign goals. We develop hooks, scripts, and creator personas tailored to your brand.",
    "how.steps.1.step": "Step 2",
    "how.steps.1.title": "Casting & Production",
    "how.steps.1.desc": "We cast authentic creators, coordinate filming, and direct on-brand UGC. Professional lighting, sound, and editing standards.",
    "how.steps.2.step": "Step 3",
    "how.steps.2.title": "Edit & Deliver",
    "how.steps.2.desc": "Fast-turnaround editing optimized for TikTok, Reels, and Shorts. Multiple formats, captions, and usage rights included.",
    "how.steps.3.step": "Step 4",
    "how.steps.3.title": "Test & Iterate",
    "how.steps.3.desc": "Track performance metrics, A/B test hooks, and refine creative strategy. Continuous optimization for maximum ROI.",
    "how.cta.packages": "View UGC Packages",

    "pricing.badge": "Transparent Pricing",
    "pricing.title.pre": "UGC Content",
    "pricing.title.highlight": "Packages",
    "pricing.subtitle": "Production-ready UGC at scale. All packages include scripting, creator casting, filming, editing, captions, and commercial usage rights.",
    "pricing.free.header": "Free UGC Strategy Call",
    "pricing.free.desc": "Get expert advice on UGC strategy, creator casting, and platform optimization before choosing a package.",
    "pricing.free.btn": "Book Free Call →",
    "pricing.plan.badge": "Get UGC",
    "pricing.price.per": "/month",
    "pricing.setup.none": "No setup fee required",
    "pricing.cta.getStarted": "Get Started",
    "pricing.footer.note": "All plans are billed monthly with no long-term contracts. Upgrade or downgrade anytime. Typical turnaround 24–72h depending on volume.",
    "pricing.sample.title": "Sample Video Included",
    "pricing.sample.desc": "New clients get <span class=\"font-bold text-[hsl(var(--brand-green))] dark:text-[hsl(var(--gold))] px-2 py-0.5 bg-[hsl(var(--brand-green))]/10 dark:bg-[hsl(var(--gold))]/20 rounded-md\">1 free sample video</span> to test our quality before committing.",
    "pricing.sample.btn": "Get Sample Video →",

    "pricing.plans.starter.name": "Starter",
    "pricing.plans.starter.deliverables": "5 UGC videos",
    "pricing.plans.starter.features.0": "5 fully-edited UGC videos",
    "pricing.plans.starter.features.1": "1-2 vetted creators",
    "pricing.plans.starter.features.2": "3 hook variations per video",
    "pricing.plans.starter.features.3": "Captions + multi-platform cuts (9:16, 1:1, 4:5)",
    "pricing.plans.starter.features.4": "60-day usage rights for paid ads",
    "pricing.plans.starter.features.5": "5-7 day turnaround",

    "pricing.plans.growth.name": "Growth",
    "pricing.plans.growth.badge": "Most Popular",
    
    "pricing.plans.growth.deliverables": "10 UGC videos",
    "pricing.plans.growth.features.0": "10 fully-edited UGC videos",
    "pricing.plans.growth.features.1": "2-3 diverse creators",
    "pricing.plans.growth.features.2": "4 hook variations per video",
    "pricing.plans.growth.features.3": "A/B testing framework + performance insights",
    "pricing.plans.growth.features.4": "Unlimited usage rights for paid ads",
    "pricing.plans.growth.features.5": "Priority 3-5 day turnaround",
    "pricing.plans.growth.features.6": "Monthly strategy call",

    "pricing.plans.scale.name": "Scale",
    "pricing.plans.scale.badge": "Best Value",
    "pricing.plans.scale.deliverables": "20 UGC videos",
    "pricing.plans.scale.features.0": "20 fully-edited UGC videos",
    "pricing.plans.scale.features.1": "4-6 creators + backup casting",
    "pricing.plans.scale.features.2": "5+ hook variations per video",
    "pricing.plans.scale.features.3": "Creative testing matrix + ROAS tracking",
    "pricing.plans.scale.features.4": "Full commercial usage rights (perpetual)",
    "pricing.plans.scale.features.5": "Rush 48-72hr delivery available",
    "pricing.plans.scale.features.6": "Bi-weekly strategy + optimization calls",
    "pricing.plans.scale.features.7": "Dedicated account manager",

    "contact.badge": "Contact Us",
    "contact.title.pre": "Tell us about",
    "contact.title.highlight": "your project",
    "contact.subtitle": "Fill out the form and we'll get back within 2 hours.",
    "contact.form.name": "Name",
    "contact.form.namePh": "Your full name",
    "contact.form.email": "Email",
    "contact.form.emailPh": "name@company.com",
    "contact.form.company": "Company",
    "contact.form.companyPh": "Your company (optional)",
    "contact.form.message": "Message",
    "contact.form.messagePh": "What do you need help with? Goals, product, timeline…",
    "contact.submit": "Send message",
    "contact.err.name": "Please enter at least 2 characters.",
    "contact.err.email": "Please enter a valid email.",
    "contact.err.message": "Please enter at least 10 characters.",
    "contact.privacy": "By submitting, you agree to be contacted. No spam, ever.",
    "contact.mailto": "hello@example.com",
    "contact.subjectPrefix": "New inquiry from",
    "contact.toast.sent": "Opening your email app…",

    "testimonials.title.pre": "Trusted by",
    "testimonials.title.highlight": "200+ Brands",
    "testimonials.subtitle": "Real results—CTR increased by 3x, ROAS improved 250%, and UGC ads outperforming studio content across DTC brands.",
    "testimonials.success.badge": "Success Story",
    "testimonials.success.title.pre": "Case Study:",
    "testimonials.success.title.highlight": "3x ROAS with UGC Ads",
    "testimonials.success.desc": "See how we helped a DTC skincare brand scale from $50K to $200K/month with authentic UGC that outperformed studio ads 3:1.",
    "testimonials.success.btn": "View Full Case Study",

    "testimonials.items.0.role": "Marketing Director",
    "testimonials.items.0.content": "Their UGC videos tripled our TikTok conversion rate. Authentic creators, fast turnaround, and hooks that actually stop the scroll. Best ROI we've seen.",
    "testimonials.items.1.role": "Founder",
    "testimonials.items.1.content": "We went from 2% CTR to 8% with their UGC ads. The creators they cast feel genuine, and the editing is platform-perfect. Scaled our brand in 60 days.",
    "testimonials.items.2.role": "CMO",
    "testimonials.items.2.content": "Game-changer for our paid social. Their UGC outperformed studio ads 3:1. Fast delivery, usage rights included, and they nailed our brand voice.",

    "tools.badge": "Platform Integrations",
    "tools.title.pre": "Seamless",
    "tools.title.highlight": "UGC Integrations",
    "tools.subtitle": "We integrate with all major ad platforms, e-commerce tools, and analytics systems—delivering UGC directly to your workflow.",
    "tools.cta.title": "Using a different platform? We adapt.",
    "tools.cta.desc": "Share your ad platform or workflow—we'll deliver UGC in the format you need, wherever you need it.",
    "tools.category.Platform": "Platform",
    "tools.category.E-commerce": "E-commerce",
    "tools.category.Analytics": "Analytics",
    "tools.category.Marketing": "Marketing",
    "tools.category.Delivery": "Delivery",
    "tools.category.Collaboration": "Collaboration",
    "tools.category.Editing": "Editing",
    "tools.category.Workflow": "Workflow",

    "faq.badge": "UGC Creation FAQs",
    "faq.title.pre": "Frequently Asked",
    "faq.title.highlight": "Questions",
    "faq.subtitle": "Everything you need to know about our UGC services—platforms, creators, usage rights, turnaround, and performance.",
    "faq.still": "Still have questions?",
    "faq.still.desc": "Our team is here to help. Get in touch and we'll respond within 2 hours.",
    "faq.packages": "View UGC Packages",
    "faq.getQuote": "Get a Quote",

    "final.badge": "Launch High‑Performing UGC",
    "final.title.pre": "Ready to Grow with",
    "final.title.highlight": "UGC?",
    "final.oneliner": "On‑brand short‑form videos that feel native and sell benefits. Script → cast → shoot → edit → deliver.",
    "final.free": "Free UGC Strategy Call • No Commitment",
    "final.reassure": "Trusted by brands to produce on‑brand, high‑converting UGC at scale.",

    "blog.badge": "UGC Insights",
    "blog.title.pre": "Blog &",
    "blog.title.highlight": "UGC Guides",
    "blog.subtitle": "Expert UGC strategies, creator casting tips, platform optimization, and performance guides to scale your content.",
    "blog.by": "By",
    "blog.read": "Read",
    "blog.posts.1.title": "UGC Hooks That Stop the Scroll: Data from 1000+ Videos",
    "blog.posts.1.excerpt": "Discover the proven hook formulas that drive 3x higher watch time and 5x better CTR on TikTok and Reels.",
    "blog.posts.1.category": "Strategy",
    "blog.posts.1.readTime": "7 min read",
    "blog.posts.2.title": "How to Cast the Perfect UGC Creator for Your Brand",
    "blog.posts.2.excerpt": "Learn the exact criteria we use to match creators to brands—demographics, tone, authenticity, and performance history.",
    "blog.posts.2.category": "Creators",
    "blog.posts.2.readTime": "6 min read",
    "blog.posts.3.title": "UGC vs Studio Ads: Why Authentic Content Wins",
    "blog.posts.3.excerpt": "Case study analysis: UGC ads outperform polished studio content 3:1 on paid social. Here's why.",
    "blog.posts.3.category": "Performance",
    "blog.posts.3.readTime": "5 min read",
    "blog.posts.4.title": "Platform-Specific UGC: TikTok vs Reels vs Shorts",
    "blog.posts.4.excerpt": "Master the nuances of each platform—pacing, captions, CTAs, and editing styles that drive conversions.",
    "blog.posts.4.category": "Platforms",
    "blog.posts.4.readTime": "8 min read",
    "blog.posts.5.title": "Scaling UGC: From 5 to 50 Videos Per Month",
    "blog.posts.5.excerpt": "The exact systems and workflows we use to scale UGC production without sacrificing quality or authenticity.",
    "blog.posts.5.category": "Scaling",
    "blog.posts.5.readTime": "9 min read",
    "blog.posts.6.title": "UGC Metrics That Matter: Beyond Views and Likes",
    "blog.posts.6.excerpt": "Track CTR, watch time, conversion rate, and ROAS—the metrics that actually predict UGC ad performance.",
    "blog.posts.6.category": "Analytics",
    "blog.posts.6.readTime": "8 min read",

    "blogDetail.notFound": "Blog Post Not Found",
    "blogDetail.returnHome": "Return to Home",
    "blogDetail.backHome": "Back to Home",
    "blogDetail.more": "More Articles",

    "case.badge": "Success Stories",
    "case.title.pre": "UGC",
    "case.title.highlight": "Success Stories",
    "case.subtitle": "See how we helped DTC brands scale revenue with authentic UGC that outperforms studio ads 3:1 on paid social.",
    "case.label.result": "Result",
    "case.label.focus": "Focus",
    "case.label.time": "Timeframe",
    "case.read.full": "View Full Case Study",
    "case.read.short": "View Study",
    "case.cta.ready": "Ready to write your own success story?",
    "case.items.1.title": "From $50K to $200K/Month with Authentic UGC",
    "case.items.1.challenge": "Studio ads were expensive and underperforming. CPAs were $85+ and ROAS was stuck at 1.8x. Needed scalable creative that converts.",
    "case.items.1.solution": "Replaced studio ads with authentic UGC from real customers. Tested creators, optimized hooks, and scaled winners across platforms.",
    "case.items.1.testimonial": "UGC ads outperformed our studio content 3:1. We scaled from $50K to $200K/month in 60 days.",
    "case.items.2.title": "TikTok UGC Strategy: 8% CTR on Cold Traffic",
    "case.items.2.challenge": "Low engagement on paid TikTok ads. CTR was 1.2% and watch time was under 2 seconds. Ads felt like ads.",
    "case.items.2.solution": "Created native TikTok UGC with trending sounds, authentic testimonials, and data-driven hooks. A/B tested 20+ variants.",
    "case.items.2.testimonial": "Our TikTok ads finally feel native. 8% CTR on cold traffic is unheard of in our niche.",
    "case.items.3.title": "Scaling UGC: 50 Videos/Month at $200/Video",
    "case.items.3.challenge": "Needed high-volume UGC for 20+ SKUs. Previous agency charged $800/video with 3-week turnaround. Couldn't scale.",
    "case.items.3.solution": "Built a creator network, batch filming workflows, and quality control systems to deliver at scale with fast turnaround.",
    "case.items.3.testimonial": "We went from 5 videos/month to 50 without sacrificing quality. Game-changer for our paid social.",

    "caseDetail.notFound": "Case Study Not Found",
    "caseDetail.returnHome": "Return to Home",
    "caseDetail.backHome": "Back to Home",
    "caseDetail.challenge": "The Challenge",
    "caseDetail.solution": "The Solution",
    "caseDetail.results": "The Results",
    "caseDetail.cta.badge": "Success Awaits",
    "caseDetail.cta.title.pre": "Ready to Achieve",
    "caseDetail.cta.title.highlight": "Similar Results?",
    "caseDetail.cta.desc": "Book a free 15-minute consultation and discover how we can help you reduce costs and scale your operations.",
    "caseDetail.cta.primary": "Book Free Consultation",
    "caseDetail.cta.secondary": "View All Case Studies",
    "caseDetail.badge.noCommitment": "No Commitment",
    "caseDetail.badge.minutes": "15 Minutes",
    "caseDetail.badge.free": "100% Free",
    "caseDetail.related.title": "More Success Stories",
    "caseDetail.related.view": "View Case Study",

    "faq.items.0.q": "What platforms do you optimize UGC for?",
    "faq.items.0.a": "TikTok, Instagram Reels, YouTube Shorts, Facebook, and Pinterest. We deliver multiple aspect ratios (9:16, 1:1, 4:5) and formats optimized for each platform's algorithm.",
    "faq.items.1.q": "How do you find and cast creators?",
    "faq.items.1.a": "We maintain a vetted network of 500+ creators across demographics. We match creators to your brand based on audience, tone, and authenticity—ensuring genuine, on-brand content.",
    "faq.items.2.q": "Do I get usage rights for the content?",
    "faq.items.2.a": "Yes. All packages include full commercial usage rights for paid ads, organic posts, and website use. No hidden fees or licensing restrictions.",
    "faq.items.3.q": "What's the typical turnaround time?",
    "faq.items.3.a": "Standard: 5–7 days from brief to final video. Rush delivery available in 48–72 hours. We provide drafts for feedback before final delivery.",
    "faq.items.4.q": "Can you create UGC for multiple products?",
    "faq.items.4.a": "Absolutely. We handle single SKUs, product bundles, and full catalog shoots. Volume discounts available for brands needing 10+ videos per month.",
    "faq.items.5.q": "How do you ensure content performs well?",
    "faq.items.5.a": "Data-driven hooks tested across 1000+ campaigns, platform-specific editing (captions, pacing, CTAs), and A/B testing frameworks. We track CTR, watch time, and conversion metrics.",
    "faq.items.6.q": "What if I don't like the content?",
    "faq.items.6.a": "Unlimited revisions on scripts and up to 2 rounds of edits on final videos. If a creator isn't the right fit, we'll recast at no extra cost. 100% satisfaction guaranteed.",
  },
  de: {
    "brand.name": "UGC Studio",
    "nav.services": "Leistungen",
    "nav.howItWorks": "Ablauf",
    "nav.pricing": "Preise",
    "nav.testimonials": "Referenzen",
    "nav.faq": "FAQ",
    "nav.contact": "Kontakt",
    "cta.getQuote": "UGC-Angebot anfordern",

    "hero.badge": "Wirkungsstarkes UGC für Marken",
    "hero.title": "UGC, das konvertiert",
    "hero.subtitle": "Wir schreiben, casten, drehen und schneiden nutzergenerierte Inhalte, die Ihr Produkt in den Mittelpunkt stellen – optimiert für TikTok, Reels und Shorts. Schnelle Umsetzung, datengetriebene Hooks, Nutzungsrechte inklusive.",
    "hero.cta.aria": "Kostenloses UGC-Strategiegespräch sichern",
    "hero.cta.full": "UGC-Angebot anfordern",
    "hero.cta.short": "Angebot",
    "hero.note": "Kostenloses Strategiegespräch + Hook-Ideen inklusive",
    "hero.stat.brands": "Betreute Marken",
    "hero.stat.videos": "Gelieferte Videos",
    "hero.stat.ctr": "Durchschn. CTR-Steigerung",

    "services.badge": "UGC Leistungen",
    "services.title.before": "End‑to‑End",
    "services.title.highlight": "UGC Produktion",
    "services.subtitle": "Script → Casting → Dreh → Schnitt → Übergabe. Kurzvideos, die nativ wirken, Vorteile verkaufen und Conversions über TikTok, Reels und Shorts steigern.",
    "services.items.0.title": "UGC-Skripting & Hooks",
    "services.items.0.description": "Hoch konvertierende Skripte mit bewährten Hooks und CTAs, zugeschnitten auf Produkt und Zielgruppe.",
    "services.items.0.benefit": "Scroll-stoppende Opener",
    "services.items.1.title": "Creator Casting",
    "services.items.1.description": "Wir finden markenpassende Creator über Nischen, Demografien und Sprechstile – passend zu Ihrem Briefing.",
    "services.items.1.benefit": "Markengerechte Gesichter",
    "services.items.2.title": "Dreh & Schnitt",
    "services.items.2.description": "End-to-End-Produktion: Regie, Licht, Ton, A‑/B‑Roll, Untertitel und Plattform-Schnitte.",
    "services.items.2.benefit": "Postfertig",
    "services.items.3.title": "Varianten & Testing",
    "services.items.3.description": "Mehrere Hooks, Winkel und Längen pro Konzept, um zu testen und das Performante zu skalieren.",
    "services.items.3.benefit": "Schnellere Learnings",
    "services.items.4.title": "Performance-Optimierung",
    "services.items.4.description": "Kreativ-Analyse und Iteration für höhere CTR, Watchtime und Conversion auf TikTok, Reels, Shorts.",
    "services.items.4.benefit": "Datengetriebene Erfolge",
    "services.items.5.title": "Nutzungsrechte & Übergabe",
    "services.items.5.description": "Klare Nutzungsrechte, Quelldateien auf Wunsch und saubere Übergabe in Ihrem bevorzugten Workspace.",
    "services.items.5.benefit": "Ohne Reibung",

    "how.badge": "Unser UGC‑Prozess",
    "how.title.pre": "So",
    "how.title.highlight": "erstellen wir UGC",
    "how.subtitle": "Vom Briefing bis zum finalen Video in 5–7 Tagen. Datengetriebene Hooks, authentische Creator und plattformspezifischer Schnitt.",
    "how.steps.0.step": "Schritt 1",
    "how.steps.0.title": "Briefing & Strategie",
    "how.steps.0.desc": "Produkt, Zielgruppe und Ziele teilen. Wir entwickeln Hooks, Skripte und Creator‑Personas passend zu Ihrer Marke.",
    "how.steps.1.step": "Schritt 2",
    "how.steps.1.title": "Casting & Produktion",
    "how.steps.1.desc": "Wir casten authentische Creator, koordinieren den Dreh und führen markenkonformes UGC. Profi‑Licht, Ton und Schnitt.",
    "how.steps.2.step": "Schritt 3",
    "how.steps.2.title": "Schnitt & Übergabe",
    "how.steps.2.desc": "Schneller Schnitt optimiert für TikTok, Reels und Shorts. Mehrere Formate, Untertitel und Nutzungsrechte inklusive.",
    "how.steps.3.step": "Schritt 4",
    "how.steps.3.title": "Testen & Iterieren",
    "how.steps.3.desc": "Performance messen, Hooks A/B‑testen und die kreative Strategie verfeinern. Kontinuierliche Optimierung für maximalen ROI.",
    "how.cta.packages": "UGC‑Pakete ansehen",

    "pricing.badge": "Transparente Preise",
    "pricing.title.pre": "UGC Content",
    "pricing.title.highlight": "Pakete",
    "pricing.subtitle": "Produktionsreifes UGC in Skalierung. Alle Pakete enthalten Skripting, Creator‑Casting, Dreh, Schnitt, Untertitel und Nutzungsrechte.",
    "pricing.free.header": "Kostenloses UGC‑Strategiegespräch",
    "pricing.free.desc": "Erhalten Sie Expertenrat zu UGC‑Strategie, Creator‑Casting und Plattform‑Optimierung vor der Paketwahl.",
    "pricing.free.btn": "Kostenlosen Call buchen →",
    "pricing.plan.badge": "UGC erhalten",
    "pricing.price.per": "/Monat",
    "pricing.setup.none": "Keine Einrichtungsgebühr erforderlich",
    "pricing.cta.getStarted": "Jetzt starten",
    "pricing.footer.note": "Alle Pläne monatlich kündbar, keine langen Verträge. Upgrade/Downgrade jederzeit. Übliche Durchlaufzeit 24–72h je nach Volumen.",
    "pricing.sample.title": "Beispielvideo inklusive",
    "pricing.sample.desc": "Neue Kund:innen erhalten <span class=\"font-bold text-[hsl(var(--brand-green))] dark:text-[hsl(var(--gold))] px-2 py-0.5 bg-[hsl(var(--brand-green))]/10 dark:bg-[hsl(var(--gold))]/20 rounded-md\">1 kostenloses Beispielvideo</span>, um unsere Qualität vorab zu testen.",
    "pricing.sample.btn": "Beispielvideo erhalten →",

    "pricing.plans.starter.name": "Starter",
    "pricing.plans.starter.deliverables": "5 UGC‑Videos",
    "pricing.plans.starter.features.0": "5 vollständig geschnittene UGC‑Videos",
    "pricing.plans.starter.features.1": "1–2 geprüfte Creator",
    "pricing.plans.starter.features.2": "3 Hook‑Varianten pro Video",
    "pricing.plans.starter.features.3": "Untertitel + Plattform‑Schnitte (9:16, 1:1, 4:5)",
    "pricing.plans.starter.features.4": "60‑Tage‑Nutzungsrechte für Paid Ads",
    "pricing.plans.starter.features.5": "5–7 Tage Durchlaufzeit",

    "pricing.plans.growth.name": "Growth",
    "pricing.plans.growth.badge": "Am beliebtesten",
    "pricing.plans.growth.deliverables": "10 UGC‑Videos",
    "pricing.plans.growth.features.0": "10 vollständig geschnittene UGC‑Videos",
    "pricing.plans.growth.features.1": "2–3 diverse Creator",
    "pricing.plans.growth.features.2": "4 Hook‑Varianten pro Video",
    "pricing.plans.growth.features.3": "A/B‑Testing‑Framework + Performance‑Insights",
    "pricing.plans.growth.features.4": "Unbegrenzte Nutzungsrechte für Paid Ads",
    "pricing.plans.growth.features.5": "Priorisierte 3–5 Tage Durchlaufzeit",
    "pricing.plans.growth.features.6": "Monatlicher Strategie‑Call",

    "pricing.plans.scale.name": "Scale",
    "pricing.plans.scale.badge": "Bestes Preis‑Leistungs‑Verhältnis",
    "pricing.plans.scale.deliverables": "20 UGC‑Videos",
    "pricing.plans.scale.features.0": "20 vollständig geschnittene UGC‑Videos",
    "pricing.plans.scale.features.1": "4–6 Creator + Backup‑Casting",
    "pricing.plans.scale.features.2": "5+ Hook‑Varianten pro Video",
    "pricing.plans.scale.features.3": "Creative‑Testing‑Matrix + ROAS‑Tracking",
    "pricing.plans.scale.features.4": "Volle kommerzielle Nutzungsrechte (perpetual)",
    "pricing.plans.scale.features.5": "Eilservice 48–72h verfügbar",
    "pricing.plans.scale.features.6": "Zweiwöchentliche Strategie‑ & Optimierungs‑Calls",
    "pricing.plans.scale.features.7": "Dedizierte Account‑Betreuung",

    "contact.badge": "Kontakt",
    "contact.title.pre": "Erzählen Sie uns von",
    "contact.title.highlight": "Ihrem Projekt",
    "contact.subtitle": "Füllen Sie das Formular aus – wir melden uns innerhalb von 2 Stunden.",
    "contact.form.name": "Name",
    "contact.form.namePh": "Ihr vollständiger Name",
    "contact.form.email": "E‑Mail",
    "contact.form.emailPh": "name@firma.com",
    "contact.form.company": "Firma",
    "contact.form.companyPh": "Ihre Firma (optional)",
    "contact.form.message": "Nachricht",
    "contact.form.messagePh": "Wobei benötigen Sie Unterstützung? Ziele, Produkt, Zeitplan…",
    "contact.submit": "Nachricht senden",
    "contact.err.name": "Bitte mindestens 2 Zeichen eingeben.",
    "contact.err.email": "Bitte eine gültige E‑Mail eingeben.",
    "contact.err.message": "Bitte mindestens 10 Zeichen eingeben.",
    "contact.privacy": "Mit dem Absenden stimmen Sie der Kontaktaufnahme zu. Kein Spam.",
    "contact.mailto": "hello@example.com",
    "contact.subjectPrefix": "Neue Anfrage von",
    "contact.toast.sent": "E‑Mail‑App wird geöffnet…",

    "testimonials.title.pre": "Vertraut von",
    "testimonials.title.highlight": "200+ Marken",
    "testimonials.subtitle": "Echte Ergebnisse – CTR x3, ROAS +250 %, UGC‑Ads schlagen Studio‑Content bei DTC‑Marken.",
    "testimonials.success.badge": "Erfolgsstory",
    "testimonials.success.title.pre": "Case Study:",
    "testimonials.success.title.highlight": "3x ROAS mit UGC‑Ads",
    "testimonials.success.desc": "So halfen wir einer DTC‑Skincare‑Marke von 50k auf 200k $/Monat mit authentischem UGC, das Studio‑Ads 3:1 übertraf.",
    "testimonials.success.btn": "Komplette Case Study ansehen",

    "testimonials.items.0.role": "Marketingleitung",
    "testimonials.items.0.content": "Ihre UGC‑Videos haben unsere TikTok‑Conversion verdreifacht. Authentische Creator, schnelle Lieferung und Hooks, die wirklich stoppen. Bestes ROI bisher.",
    "testimonials.items.1.role": "Gründer",
    "testimonials.items.1.content": "Von 2 % CTR auf 8 % mit ihren UGC‑Ads. Die gecasteten Creator wirken echt, der Schnitt ist plattformgerecht. In 60 Tagen skaliert.",
    "testimonials.items.2.role": "CMO",
    "testimonials.items.2.content": "Game‑Changer für unser Paid Social. Ihr UGC schlug Studio‑Ads 3:1. Schnelle Lieferung, Nutzungsrechte inklusive, Brand‑Voice perfekt getroffen.",

    "tools.badge": "Plattform‑Integrationen",
    "tools.title.pre": "Nahtlose",
    "tools.title.highlight": "UGC‑Integrationen",
    "tools.subtitle": "Wir integrieren mit allen führenden Ad‑Plattformen, E‑Commerce‑Tools und Analytics‑Systemen – und liefern UGC direkt in Ihren Workflow.",
    "tools.cta.title": "Andere Plattform? Wir passen uns an.",
    "tools.cta.desc": "Teilen Sie Ihre Plattform oder Ihren Workflow – wir liefern UGC im benötigten Format, wo immer Sie es brauchen.",
    "tools.category.Platform": "Plattform",
    "tools.category.E-commerce": "E‑Commerce",
    "tools.category.Analytics": "Analytics",
    "tools.category.Marketing": "Marketing",
    "tools.category.Delivery": "Auslieferung",
    "tools.category.Collaboration": "Zusammenarbeit",
    "tools.category.Editing": "Schnitt",
    "tools.category.Workflow": "Workflow",

    "faq.badge": "UGC‑FAQ",
    "faq.title.pre": "Häufig gestellte",
    "faq.title.highlight": "Fragen",
    "faq.subtitle": "Alles zu unseren UGC‑Services – Plattformen, Creator, Nutzungsrechte, Durchlaufzeit und Performance.",
    "faq.still": "Noch Fragen?",
    "faq.still.desc": "Unser Team hilft gern. Wir antworten innerhalb von 2 Stunden.",
    "faq.packages": "UGC‑Pakete ansehen",
    "faq.getQuote": "Angebot anfordern",

    "final.badge": "Leistungsstarkes UGC starten",
    "final.title.pre": "Bereit zu wachsen mit",
    "final.title.highlight": "UGC?",
    "final.oneliner": "Markengerechte Kurzvideos, die nativ wirken und Vorteile verkaufen. Script → Casting → Dreh → Schnitt → Übergabe.",
    "final.free": "Kostenloses UGC‑Strategiegespräch • Keine Verpflichtung",
    "final.reassure": "Vertrauenswürdig für markenkonformes, stark konvertierendes UGC in Skalierung.",

    "blog.badge": "UGC Insights",
    "blog.title.pre": "Blog &",
    "blog.title.highlight": "UGC‑Guides",
    "blog.subtitle": "Expertenstrategien für UGC, Casting‑Tipps, Plattform‑Optimierung und Performance‑Guides für Ihr Wachstum.",
    "blog.by": "Von",
    "blog.read": "Lesen",
    "blog.posts.1.title": "UGC‑Hooks, die stoppen: Daten aus 1000+ Videos",
    "blog.posts.1.excerpt": "Bewährte Hook‑Formeln für 3x längere Watchtime und 5x höhere CTR auf TikTok und Reels.",
    "blog.posts.1.category": "Strategie",
    "blog.posts.1.readTime": "7 Min.",
    "blog.posts.2.title": "Den perfekten UGC‑Creator für Ihre Marke casten",
    "blog.posts.2.excerpt": "Unsere Kriterien für Creator‑Matching – Demografie, Tonalität, Authentizität und Performance‑Historie.",
    "blog.posts.2.category": "Creator",
    "blog.posts.2.readTime": "6 Min.",
    "blog.posts.3.title": "UGC vs. Studio‑Ads: Warum Authentizität gewinnt",
    "blog.posts.3.excerpt": "Case Study: UGC‑Ads schlagen polierte Studio‑Spots 3:1 im Paid Social. Deshalb.",
    "blog.posts.3.category": "Performance",
    "blog.posts.3.readTime": "5 Min.",
    "blog.posts.4.title": "Plattform‑spezifisches UGC: TikTok vs Reels vs Shorts",
    "blog.posts.4.excerpt": "Nuancen pro Plattform – Tempo, Untertitel, CTAs und Schnittstile, die konvertieren.",
    "blog.posts.4.category": "Plattformen",
    "blog.posts.4.readTime": "8 Min.",
    "blog.posts.5.title": "UGC skalieren: Von 5 auf 50 Videos/Monat",
    "blog.posts.5.excerpt": "Unsere Systeme und Workflows, um UGC in Menge zu liefern – ohne Qualitätsverlust.",
    "blog.posts.5.category": "Skalierung",
    "blog.posts.5.readTime": "9 Min.",
    "blog.posts.6.title": "Wichtige UGC‑Metriken: Mehr als Views und Likes",
    "blog.posts.6.excerpt": "Tracken Sie CTR, Watchtime, Conversion und ROAS – die echten Performance‑Treiber.",
    "blog.posts.6.category": "Analytics",
    "blog.posts.6.readTime": "8 Min.",

    "blogDetail.notFound": "Blogartikel nicht gefunden",
    "blogDetail.returnHome": "Zur Startseite",
    "blogDetail.backHome": "Zurück zur Startseite",
    "blogDetail.more": "Weitere Artikel",

    "blog.detail.1.content": "\n      <h2>Top‑Hook‑Muster</h2>\n      <ul>\n        <li>Problem–Agitieren–Lösen‑Opener</li>\n        <li>Pattern Interrupts und Neugier‑Gaps</li>\n        <li>Social Proof und Autoritäts‑Hooks</li>\n        <li>Vorher/Nachher‑Transformationen</li>\n      </ul>\n    ",
    "blog.detail.2.content": "\n      <h2>Casting‑Kriterien</h2>\n      <ul>\n        <li>Zielgruppen‑Demografie und ‑Psychografie</li>\n        <li>On‑Camera‑Präsenz und Authentizität</li>\n        <li>Frühere UGC‑Performance‑Metriken</li>\n        <li>Markenfit und Tonalität</li>\n      </ul>\n    ",
    "blog.detail.3.content": "\n      <h2>Wichtigste Erkenntnisse</h2>\n      <ul>\n        <li>Authentizität steigert Vertrauen und Engagement</li>\n        <li>Algorithmen bevorzugen nativen Content</li>\n        <li>Niedrigere Produktionskosten, höherer ROAS</li>\n        <li>Schnellere Iteration und A/B‑Tests</li>\n      </ul>\n    ",
    "blog.detail.4.content": "\n      <h2>Plattform‑Unterschiede</h2>\n      <ul>\n        <li>TikTok: Schnelle Cuts, Trendsounds, nativer Look</li>\n        <li>Reels: Poliertes UGC, starke Hooks, Storytelling</li>\n        <li>Shorts: Kompakter Nutzen, direkte CTAs</li>\n        <li>Cross‑Plattform‑Optimierung</li>\n      </ul>\n    ",
    "blog.detail.5.content": "\n      <h2>Skalierungs‑Framework</h2>\n      <ul>\n        <li>Creator‑Netzwerk ausbauen</li>\n        <li>Batch‑Dreh und Schnitt‑Workflows</li>\n        <li>Qualitätssicherung und Brand‑Guidelines</li>\n        <li>Performance‑Tracking und Iteration</li>\n      </ul>\n    ",
    "blog.detail.6.content": "\n      <h2>Schlüsselmetriken</h2>\n      <ul>\n        <li>Hook‑Rate und 3‑Sekunden‑Watchtime</li>\n        <li>CTR und Landing‑Page‑CVR</li>\n        <li>CPA und ROAS</li>\n        <li>Creative Fatigue und Refresh‑Zyklen</li>\n      </ul>\n    ",

    "case.badge": "Erfolgsstories",
    "case.title.pre": "UGC",
    "case.title.highlight": "Erfolgsstories",
    "case.subtitle": "So halfen wir DTC‑Marken, Umsatz zu skalieren – mit authentischem UGC, der Studio‑Ads 3:1 schlägt.",
    "case.label.result": "Ergebnis",
    "case.label.focus": "Fokus",
    "case.label.time": "Zeitrahmen",
    "case.read.full": "Komplette Case Study",
    "case.read.short": "Zur Studie",
    "case.cta.ready": "Bereit für Ihre eigene Erfolgsstory?",
    "case.items.1.title": "Von 50k auf 200k $/Monat mit authentischem UGC",
    "case.items.1.challenge": "Studio‑Ads waren teuer und schwach. CPA > 85 $, ROAS 1,8x. Benötigt: skalierbare, konvertierende Creatives.",
    "case.items.1.solution": "Studio‑Ads durch authentisches UGC echter Kund:innen ersetzt. Creator getestet, Hooks optimiert und Gewinner skaliert.",
    "case.items.1.testimonial": "UGC‑Ads übertrafen unsere Studio‑Spots 3:1. In 60 Tagen von 50k auf 200k $/Monat skaliert.",
    "case.items.2.title": "TikTok‑UGC‑Strategie: 8 % CTR auf kaltem Traffic",
    "case.items.2.challenge": "Geringe Interaktion bei TikTok‑Ads. CTR 1,2 %, Watchtime < 2 s. Ads wirkten wie Ads.",
    "case.items.2.solution": "Natives TikTok‑UGC mit Trendsounds, echten Testimonials und datengetriebenen Hooks. 20+ Varianten A/B‑getestet.",
    "case.items.2.testimonial": "Unsere TikTok‑Ads fühlen sich endlich nativ an. 8 % CTR auf kaltem Traffic ist in unserer Nische außergewöhnlich.",
    "case.items.3.title": "UGC skalieren: 50 Videos/Monat für 200 $/Video",
    "case.items.3.challenge": "Hohes Volumen für 20+ SKUs nötig. Voragentur: 800 $/Video, 3 Wochen. Nicht skalierbar.",
    "case.items.3.solution": "Creator‑Netzwerk aufgebaut, Batch‑Workflows und Qualitätskontrolle etabliert. Schnelle Lieferung in Skalierung.",
    "case.items.3.testimonial": "Von 5 auf 50 Videos/Monat – ohne Qualitätsverlust. Game‑Changer für unser Paid Social.",

    "caseDetail.notFound": "Case Study nicht gefunden",
    "caseDetail.returnHome": "Zur Startseite",
    "caseDetail.backHome": "Zurück zur Startseite",
    "caseDetail.challenge": "Die Herausforderung",
    "caseDetail.solution": "Die Lösung",
    "caseDetail.results": "Die Ergebnisse",
    "caseDetail.cta.badge": "Erfolg wartet",
    "caseDetail.cta.title.pre": "Bereit für",
    "caseDetail.cta.title.highlight": "ähnliche Ergebnisse?",
    "caseDetail.cta.desc": "Buchen Sie ein kostenloses 15‑Minuten‑Gespräch und erfahren Sie, wie wir Kosten senken und skalieren helfen.",
    "caseDetail.cta.primary": "Kostenlose Beratung buchen",
    "caseDetail.cta.secondary": "Alle Case Studies ansehen",
    "caseDetail.badge.noCommitment": "Ohne Verpflichtung",
    "caseDetail.badge.minutes": "15 Minuten",
    "caseDetail.badge.free": "100% kostenlos",
    "caseDetail.related.title": "Weitere Erfolgsstories",
    "caseDetail.related.view": "Case Study ansehen",

    "faq.items.0.q": "Für welche Plattformen optimiert ihr UGC?",
    "faq.items.0.a": "TikTok, Instagram Reels, YouTube Shorts, Facebook und Pinterest. Wir liefern mehrere Seitenverhältnisse (9:16, 1:1, 4:5) und plattformspezifische Formate.",
    "faq.items.1.q": "Wie findet und castet ihr Creator?",
    "faq.items.1.a": "Wir haben ein geprüftes Netzwerk von 500+ Creatorn. Matching nach Zielgruppe, Tonalität und Authentizität – für markengerechten Content.",
    "faq.items.2.q": "Erhalte ich Nutzungsrechte für den Content?",
    "faq.items.2.a": "Ja. Alle Pakete beinhalten volle kommerzielle Nutzungsrechte für Ads, organische Posts und Website. Keine versteckten Gebühren.",
    "faq.items.3.q": "Wie lange dauert die Umsetzung?",
    "faq.items.3.a": "Standard: 5–7 Tage vom Briefing bis zum finalen Video. Eilservice in 48–72 Stunden verfügbar. Feedback‑Runden inklusive.",
    "faq.items.4.q": "Erstellt ihr UGC für mehrere Produkte?",
    "faq.items.4.a": "Absolut. Einzelne SKUs, Bundles oder kompletter Katalog. Mengennachlass ab 10+ Videos pro Monat.",
    "faq.items.5.q": "Wie stellt ihr Performance sicher?",
    "faq.items.5.a": "Datengetriebene Hooks aus 1000+ Kampagnen, plattformspezifischer Schnitt (Untertitel, Pace, CTAs) und A/B‑Tests. Wir tracken CTR, Watchtime und Conversions.",
    "faq.items.6.q": "Was, wenn mir der Content nicht gefällt?",
    "faq.items.6.a": "Unbegrenzte Skript‑Revisionen und bis zu 2 Edits pro Finalvideo. Passt ein Creator nicht, recasten wir kostenlos. 100% Zufriedenheit garantiert.",
  },
};

const LanguageContext = createContext<LanguageContextState | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    const saved = (typeof window !== "undefined" && localStorage.getItem(storageKey)) as Lang | null;
    return saved ?? defaultLang;
  });

  useEffect(() => {
    try {
      localStorage.setItem(storageKey, lang);
    } catch {
      void 0;
    }
  }, [lang]);

  const setLang = (l: Lang) => setLangState(l);

  const t = useMemo(() => {
    const dict = dictionaries[lang] ?? dictionaries[defaultLang];
    return (key: string) => dict[key] ?? dictionaries[defaultLang][key] ?? key;
  }, [lang]);

  const value = useMemo(() => ({ lang, setLang, t }), [lang, t]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
